# Generated by Django 6.1 on 2026-09-02 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epreuves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epreuve',
            name='description',
        ),
        migrations.RemoveField(
            model_name='epreuve',
            name='titre',
        ),
        migrations.AddField(
            model_name='epreuve',
            name='entite',
            field=models.CharField(choices=[('FAST', 'FAST'), ('FST', 'FST')], default='FAST', max_length=100),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='epreuves.matiere'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='niveau',
            field=models.CharField(choices=[('1', '1ère année'), ('2', '2ème année'), ('3', '3ème année')], max_length=100),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='type_examen',
            field=models.CharField(choices=[('CC', 'Contrôle Continu'), ('EX', 'Examen Final')], max_length=100),
        ),
    ]
