# Generated by Django 6.1 on 2026-09-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epreuves', '0002_remove_epreuve_description_remove_epreuve_titre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epreuve',
            name='type_examen',
        ),
        migrations.AddField(
            model_name='epreuve',
            name='session',
            field=models.CharField(choices=[('Examen', 'Examen Final'), ('Rattrapage', 'Rattrapage')], default='Quel est la session?', max_length=100),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='entite',
            field=models.CharField(choices=[('FAST', 'FAST'), ('ENS', 'ENS')], default='FAST', max_length=100),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='niveau',
            field=models.CharField(choices=[('1', '1ère année'), ('2', '2ème année'), ('3', '3ème année')], default='Choisissez votre niveau', max_length=100),
        ),
    ]
