# Generated by Django 6.1 on 2026-09-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epreuves', '0003_remove_epreuve_type_examen_epreuve_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epreuve',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='epreuves.matiere'),
        ),
    ]
