# Generated by Django 6.1 on 2026-09-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epreuves', '0005_alter_epreuve_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epreuve',
            name='annee',
            field=models.IntegerField(choices=[(2020, '2020-2021'), (2021, '2021-2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026')]),
        ),
    ]
